// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2s0-Z-T8EOtEU8F6kn7W3D0xFpq77MEI',
    appId: '1:275849439186:web:995bb78950fcd6f2d84a0b',
    messagingSenderId: '275849439186',
    projectId: 'mobile-project-dc052',
    authDomain: 'mobile-project-dc052.firebaseapp.com',
    storageBucket: 'mobile-project-dc052.firebasestorage.app',
    measurementId: 'G-287E2PLRGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYzG8FMUZhwNc6yPC94s7-QcMprylJes',
    appId: '1:275849439186:android:cbbe24a7bc221ad0d84a0b',
    messagingSenderId: '275849439186',
    projectId: 'mobile-project-dc052',
    storageBucket: 'mobile-project-dc052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZMG5uv5FY3xED3-59ba-0Iox2Ih74KjA',
    appId: '1:275849439186:ios:93dd79c9b0e4e3c4d84a0b',
    messagingSenderId: '275849439186',
    projectId: 'mobile-project-dc052',
    storageBucket: 'mobile-project-dc052.firebasestorage.app',
    iosBundleId: 'com.example.mobilelecture1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZMG5uv5FY3xED3-59ba-0Iox2Ih74KjA',
    appId: '1:275849439186:ios:93dd79c9b0e4e3c4d84a0b',
    messagingSenderId: '275849439186',
    projectId: 'mobile-project-dc052',
    storageBucket: 'mobile-project-dc052.firebasestorage.app',
    iosBundleId: 'com.example.mobilelecture1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2s0-Z-T8EOtEU8F6kn7W3D0xFpq77MEI',
    appId: '1:275849439186:web:ea75119cea9138b5d84a0b',
    messagingSenderId: '275849439186',
    projectId: 'mobile-project-dc052',
    authDomain: 'mobile-project-dc052.firebaseapp.com',
    storageBucket: 'mobile-project-dc052.firebasestorage.app',
    measurementId: 'G-R61TNJF3GT',
  );
}
